### ISSUE TITLE
User does not get email on multiple email accounts

### ISSUE THREAD

**Issue by annastoilova** [tiki/app#217] opened 2021-07-16 14:53 UTC
"Ive already checked spam and just rechecked now nothing there.. ive try with gmail, hotmail and a work email @rona.ca and none of them where able to received the registration email."

Shane: Any insight on a user who is not getting a registration email sent to them (multiple email tries & not in spam) sendgrid? bug? us? them?

wolfien@gmail.com is the email he used to contact
User based in canada i think

**Comment by ricardobrg** [comment] 2021-12-06 22:40
Was it addressed?

**Comment by mike-audi** [comment] 2021-12-07 01:44
unable to reproduce. only happens for the one user. closing for now.

**Closed by mike-audi** 2021-12-07 01:44 UTC
Labels: bug, question, P3
